Repository Puh00/toru-bot, pull requests merged in 2021-07, with the labels that each got.

#25 Fix !8ball no response when given no args
  cogs/magic8ball.py
Labels: bug

#26 Replace all print() with logging for better info structure
  cogs/music.py
  cogs/poll.py
  toru.py
  util/torudb.py
Labels: enhancement

#29 Refactor/joke
  cogs/joke.py
  util/joke_handler.py
Labels: documentation, enhancement

#31 Rework/rpgchat
  cogs/chat.py
  cogs/rpgchat.py
  util/error_handler.py
  util/toru_rpg.py
  util/torudb.py
Labels: bug, documentation, enhancement

#33 ⬇️ downgrade mongo image from latest to 4.4.6
  docker-compose-production.yml
Labels: bug

#34 ✨ Update chat.py, it's now possible to see other people's level and exp
  cogs/chat.py
Labels: enhancement

#35 Refactor/admin
  cogs/admin.py
  util/hacks.py
  util/time_parser.py
  util/torudb.py
Labels: bug

#36 Feature/translation
  cogs/translate.py
  util/ascii_table.py
Labels: enhancement
